#ifndef SSL_CTX_H_
#define SSL_CTX_H_

#include <openssl/ssl.h>

enum SSL_METHOD_ENUM {
    TLS_METHOD,
    TLS_SERVER_METHOD,
    TLS_CLIENT_METHOD,
    SSL_V23_METHOD,
    SSL_V23_SERVER_METHOD,
    SSL_V23_CLIENTH_METHOD,
    SSL_V3_METHOD,
    SSL_V3_SERVER_METHOD,
    SSL_V3_CLIENTH_METHOD,
    TLS_V1_METHOD,
    TLS_V1_SERVER_METHOD,
    TLS_V1_CLIENT_METHOD,
    TLS_V1_1_METHOD,
    TLS_V1_1_SERVER_METHOD,
    TLS_V1_1_CLIENT_METHOD,
    TLS_V1_2_METHOD,
    TLS_V1_2_SERVER_METHOD,
    TLS_V1_2_CLIENT_METHOD,
    DTLS_METHOD,
    DTLS_SERVER_METHOD,
    DTLS_CLIENT_METHOD,
    DTLS_V1_METHOD,
    DTLS_V1_SERVER_METHOD,
    DTLS_V1_CLIENT_METHOD,
    DTLS_V1_2_METHOD,
    DTLS_V1_2_SERVER_METHOD,
    DTLS_V1_2_CLIENT_METHOD
};

class SSLCtx
{
    const SSL_METHOD*   getSSLMethod(int index);
    SSL_CTX*            makeNewSSLCTX(const SSL_METHOD* sslMethod);
    void                freeSSLCTX(SSL_CTX* ctx);
};

#endif